### ISSUE TITLE
Cannot get the correct APIKey for the QueryLens

### ISSUE THREAD

**Issue by hanglics** [hscells/querylens#3]
![Screen Shot 2020-01-14 at 21 48 48](https://user-images.githubusercontent.com/5422705/72342229-c1000180-3717-11ea-85c2-5ced96d2479f.png)

I cannot detect where the problem is for this bug, the `s.Config.Entrez.APIKey` and `s.Config.Entrez.Email` can be accessed from anywhere in `main.go`, even for the `s.Entrez` is getting the correct APIKey, but this error persists, no matter how I change the APIKey or test the code in `server.go` or `main.go`, it keeps getting the ip address for APIKey.

EDIT: The error is thrown by line 662 in `transformations.go` by calling 
```
cuis, err := formulation.NewMedGenExpander(c.EntrezStatisticsSource).CUIs(q)
```

**Comment by hscells** [comment]
I think this is resolved.
